# Assignments

### Question 2.2
2.2 Write a program that uses input to prompt a user for their name and then welcomes them. Note that input will pop up a dialog box. Enter Sarah in the pop-up box when you are prompted so your output will match the desired output.

In [2]:
# Solution to Question 2.2
name = input("Enter your name")
print("Hello", name)

Enter your nameIddi Abdul Aziz
Hello Iddi Abdul Aziz


### Question 2.3
2.3 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking or bad user data.

In [1]:
# Solution to Question 2.3
hours = input("Enter Hours: ")
rate = input("Enter rate: ")
pay = float(hours) * float(rate)
print(pay)

Enter Hours: 35
Enter rate: 2.75
96.25


### Question 3.1
3.1 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.

In [4]:
# Solution to Question 3.1

hrs = input("Enter Hours:")
h = float(hrs)
zz = input("Enter the Rate:")
z = float(zz)
if h <= 40:
    print(h * z)
elif h > 40:
    print(40 * z + (h - 40) * 1.5 * z)

Enter Hours:45
Enter the Rate:10.50
498.75


### Question 3.3
3.3 Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
Score Grade
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.

In [7]:
# Solution to Question 3.3
score = input("Enter Score: ")
z = float(score)
if 0.0 <= z <= 1.0:
    if z >= 0.9:
        result = "A"
        print(result)
    elif 0.8 <= z < 0.9:
        result = "B"
        print(result)
    elif 0.7 <= z < 0.8:
        result = "C"
        print(result)
    elif 0.6 <= z < 0.7:
        result = "D"
        print(result)
    else:
        reult = "F"
        print(result)
else:
    print("Error: score out of range")

Enter Score: 0.8
B


### Question 4.6
4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.

In [8]:
# Solution to Question 4.6

def computepay(h,r):
    if h <= 40:
        pay = h * r
    elif h > 40:
        pay = 40 * r + (h-40) * r * 1.5
    return pay
# buld a function to compute payment first.
hrs = input("Enter Hours:")
h = float(hrs)
rate = input("Enter rate:")
r = float(rate)
p = computepay(h,r) 
print(p)

Enter Hours:45
Enter rate:10.50
498.75


### Question 5.2
5.2 Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.

In [9]:
# Solution to Question 5.2
largest = None
smallest = None
while True:
    try:
    	num = input("Enter a number: ")
    	if num == "done" : 
        	break
    	num = int(num)
    	if largest is None or largest < num:
        	largest = num
    	elif smallest is None or smallest > num:
        	smallest = num
    except ValueError:
        print("Invalid input")
print('Maximum is', largest)
print('Minimum is', smallest)

Enter a number: 7
Enter a number: 2
Enter a number: bob
Invalid input
Enter a number: 10
Enter a number: 4
Enter a number: done
Maximum is 10
Minimum is 2


In [1]:
# Solution to Question 5.2 
# ALternative
minima = maxima = None
while True:
    user_input = input("Number or 'done': ")
    if user_input == 'done':
        break
    elif user_input.isdigit():
        num = int(user_input)
        if maxima is None or num > maxima: maxima = num
        if minima is None or num < minima: minima = num
    else:
        print("Input not recorgnized.")
print("Maxima is {}".format(maxima)) 
print("Minima is {}".format(minima)) 

Number or 'done': 7
Number or 'done': 2
Number or 'done': bob
Input not recorgnized.
Number or 'done': 10
Number or 'done': 4
Number or 'done': done
Maxima is 10
Minima is 2
